# Generated by Django 2.1.7 on 2019-03-08 18:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField()),
                ('original_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('latest_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'registration',
            },
        ),
    ]
