# Generated by Django 2.1.7 on 2019-03-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsnap_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
