# Generated by Django 2.2 on 2019-04-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsnap_registration', '0003_auto_20190416_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='modified_date',
            new_name='modified_at',
        ),
    ]
