# Generated by Django 2.1.7 on 2019-04-08 22:01

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dsnap_registration', '0004_auto_20190416_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration',
            name='original_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(editable=False),
        ),
    ]
