# Generated by Django 2.2 on 2019-04-16 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dsnap_registration', '0005_auto_20190419_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='rules_service_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='user_approved',
            field=models.BooleanField(null=True),
        ),
    ]
